### ISSUE TITLE
I forgot an assert here

### ISSUE THREAD

**Issue by rhymu8354** [rhymu8354/Utf8#1]
https://github.com/rhymu8354/Utf8/blob/37420f3f4d518eb68fb8e4b49837ac117ac2a0cb/test/src/Utf8Tests.cpp#L15-L18

Credit goes to collinstevens for finding this.  Thanks!

**Comment by collinstevens** [comment]
Just doing some snooping. ;)

**Comment by rhymu8354** [comment]
Fixed!  Thanks again!
